vrc-get repo add https://adjerry91.github.io/VRCFaceTracking-Templates/index.json || true
vrc-get repo add https://api.vrlabs.dev/listings/category/Components || true
vrc-get repo add https://api.vrlabs.dev/listings/category/Dependencies || true
vrc-get repo add https://api.vrlabs.dev/listings/category/Essentials || true
vrc-get repo add https://api.vrlabs.dev/listings/category/Systems || true
vrc-get repo add https://codec-xyz.github.io/photo_frame_manager/index.json || true
vrc-get repo add https://drblackrat.github.io/vpm-listing/index.json || true
vrc-get repo add https://enitimeago.github.io/vpm-repos/index.json || true
vrc-get repo add https://esperecyan.github.io/VRMConverterForVRChat/registry.json || true
vrc-get repo add https://furality.github.io/vcc-packages/index.json || true
vrc-get repo add https://github.com/Krysiek/CuteDancer/raw/vpm/CuteDancer.json || true
vrc-get repo add https://hai-vr.github.io/vpm-listing/index.json || true
vrc-get repo add https://kemocade.github.io/Kemocade.Vrc.Data.Extensions/index.json || true
vrc-get repo add https://krysiek.github.io/CuteDancer/index.json || true
vrc-get repo add https://kurone-kito.github.io/vpm/index.json || true
vrc-get repo add https://kurotu.github.io/vpm-repos/vpm.json || true
vrc-get repo add https://labthe3rd.github.io/PZCameraSystem/index.json || true
vrc-get repo add https://lilxyzw.github.io/vpm-repos/vpm.json || true
vrc-get repo add https://magmamcnet.github.io/VPM/index.json || true
vrc-get repo add https://mmmaellon.github.io/MMMaellonVCCListing/index.json || true
vrc-get repo add https://orels1.github.io/orels-Unity-Shaders/index.json || true
vrc-get repo add https://poiyomi.github.io/vpm/index.json || true
vrc-get repo add https://pokeyi.dev/vpm-packages/index.json || true
vrc-get repo add https://repo.buddyworks.wtf/index.json || true
vrc-get repo add https://spokeek.github.io/vpm-repository/index.json || true
vrc-get repo add https://suzuryg.github.io/vpm-repos/vpm.json || true
vrc-get repo add https://vcc.pawlygon.net/index.json || true
vrc-get repo add https://vcc.vrcfury.com/ || true
vrc-get repo add https://vpm.anatawa12.com/vpm.json || true
vrc-get repo add https://vpm.benjifox.gay/index.json || true
vrc-get repo add https://vpm.dreadscripts.com/listings/main.json || true
vrc-get repo add https://vpm.nadena.dev/vpm.json || true
vrc-get repo add https://vpm.pimaker.at/index.json || true
vrc-get repo add https://vpm.techanon.dev/index.json || true
vrc-get repo add https://vpm.thry.dev/index.json || true
vrc-get repo add https://wholesomevr.github.io/SPS-Configurator/index.json || true
vrc-get repo add https://i5ucc.github.io/vpm/main.json || true
vrc-get repo add https://pandrabox.github.io/vpm/index.json || true
vrc-get repo add https://kb10uy.github.io/vrc-repository/index.json || true
vrc-get repo add https://tr1turbo.github.io/BlendShare/index.json || true
vrc-get repo add https://waya0125.com/vpm || true
vrc-get repo add https://foxscore.dev/vpm/index.json || true
vrc-get repo add https://tliks.github.io/vpm-repos/index.json || true
vrc-get repo add https://www.matthewherber.com/Happys-VRC-tools/index.json || true
vrc-get repo add https://d4rkc0d3r.github.io/vpm-repos/main.json || true
vrc-get repo add https://vpm.narazaka.net/index.json || true
vrc-get repo add https://xtlcdn.github.io/vpm/index.json || true
vrc-get repo add https://vpm.bluwizard.net/index.json || true
vrc-get repo add https://aurycat.github.io/vpm/index.json || true
vrc-get repo add https://lastationvrchat.github.io/Lastation-Package-Listing/index.json || true
vrc-get repo add https://vpm.ureishi.net/repos.json || true
vrc-get repo add https://vpm.vrsl.dev/index.json || true
vrc-get repo add https://nidonocu.github.io/virtual-gryphon-packages/index.json || true
vrc-get repo add https://z3y.github.io/vpm-package-listing/index.json || true
vrc-get repo add https://page.853lab.com/vpm-repos/vpm.json || true
vrc-get repo add https://hoyotoon.github.io/vpm/index.json || true
vrc-get repo add https://tmyt.github.io/vpm/index.json || true
vrc-get repo add https://rerigferl.github.io/vpm/vpm.json || true
vrc-get repo add https://vrctxl.github.io/VPM/index.json || true
vrc-get repo add https://guribo.github.io/TLP/index.json || true
vrc-get repo add https://cyanlaser.github.io/CyanPlayerObjectPool/index.json || true
vrc-get repo add https://reava.github.io/VPM-Listings/index.json || true
vrc-get repo add https://vavassor.github.io/OrchidSealVPM/index.json || true
vrc-get repo add https://virtualvisions.github.io/VPM-Packages/index.json || true
vrc-get repo add https://vpm.gyoku.tech/vpm.json || true
vrc-get repo add https://pkg-index.yuxiaviation.com/ || true
vrc-get repo add https://orels1.github.io/UdonToolkit/index.json || true
vrc-get repo add https://vrcd-community.github.io/vpm-packages/index.json || true
vrc-get repo list
vrc-get resolve
vrc-get remove dev.foxscore.easy-login -y || true
vrc-get remove au.benjithatfoxguy.templates.world.2022.3.22f1.updater -y || true
vrc-get remove com.nidonocu.vrcunitytoolbar -y || true
vrc-get remove au.benjithatfoxguy.batchimportunitypackage -y || true
vrc-get remove au.benjithatfoxguy.restartunity -y || true
vrc-get remove dev.hai-vr.resilience.let-me-see -y || true
vrc-get remove dev.hai-vr.resilience.toolkit -y || true
vrc-get remove unity-editor-dark-mode -y || true
rm -rf Assets/Editor || true
rm -rf Assets/Editor.meta || true
rm -rf Assets/UERP || true
rm -rf Assets/UERP.meta || true
vrc-get install com.yuxiaviation.vrchat.autobuild.world -y || true
vrc-get install cn.org.vrcd.vpm.vrchat-sdk-patcher.worlds -y || true